// DESIGN REFERENCE — Generated by Claude App for Cadu
// This is the GOLD STANDARD for UI quality. Mr. Musk must match this level.
// This file is reference only — do NOT import it. Adapt the patterns to our Next.js app.

import { useState } from "react";

const C = {
 bg0: "#08080A", bg1: "#0F0F12", bg2: "#141418", bg3: "#1A1A20",
 border1: "#1F1F26", border2: "#252530", border3: "#2D2D3A",
 text1: "#F4F4F6", text2: "#A0A0B0", text3: "#606070", text4: "#303040",
 amber: "#F0A500", amberHover: "#C88800", amberBg: "#F0A50015", amberBorder: "#F0A50030",
 red: "#EF4444", redBg: "#EF444415", redBorder: "#EF444430",
 yellow: "#F59E0B", yellowBg: "#F59E0B15", yellowBorder: "#F59E0B30",
 blue: "#3B82F6", blueBg: "#3B82F615", blueBorder: "#3B82F630",
 green: "#10B981", greenBg: "#10B98115", greenBorder: "#10B98130",
 stages: {
 analise: "#60A5FA", contestacao: "#F59E0B", probatoria: "#A78BFA",
 sentenca: "#FBBF24", recurso: "#F87171", execucao: "#34D399", encerrado: "#4B5563"
 }
};

const fmt = (v) => `R$ ${v.toLocaleString("pt-BR", { minimumFractionDigits: 0 })}`;

const clientes = [
 {
 id: 1, sigla: "LA", nome: "LATAM Airlines", cor: "#F0A500",
 processos: 47, urgentes: 3, prazoHoje: 2, prazoSemana: 7,
 valorRisco: 1240000, taxaExito: 71,
 pipeline: { analise: 11, contestacao: 16, probatoria: 8, sentenca: 5, recurso: 4, execucao: 3 },
 ultimaAtt: "12 min"
 },
 {
 id: 2, sigla: "BS", nome: "Banco Safra", cor: "#60A5FA",
 processos: 31, urgentes: 1, prazoHoje: 0, prazoSemana: 4,
 valorRisco: 870000, taxaExito: 78,
 pipeline: { analise: 7, contestacao: 11, probatoria: 5, sentenca: 4, recurso: 2, execucao: 2 },
 ultimaAtt: "1h"
 },
 {
 id: 3, sigla: "CB", nome: "Claro Brasil", cor: "#34D399",
 processos: 28, urgentes: 4, prazoHoje: 1, prazoSemana: 6,
 valorRisco: 640000, taxaExito: 65,
 pipeline: { analise: 8, contestacao: 9, probatoria: 4, sentenca: 3, recurso: 3, execucao: 1 },
 ultimaAtt: "34 min"
 },
 {
 id: 4, sigla: "ML", nome: "Magazine Luiza", cor: "#A78BFA",
 processos: 19, urgentes: 0, prazoHoje: 0, prazoSemana: 2,
 valorRisco: 320000, taxaExito: 82,
 pipeline: { analise: 5, contestacao: 7, probatoria: 3, sentenca: 2, recurso: 1, execucao: 1 },
 ultimaAtt: "3h"
 },
 {
 id: 5, sigla: "VV", nome: "Vivo Telecom", cor: "#F87171",
 processos: 14, urgentes: 1, prazoHoje: 1, prazoSemana: 3,
 valorRisco: 290000, taxaExito: 69,
 pipeline: { analise: 4, contestacao: 5, probatoria: 2, sentenca: 1, recurso: 1, execucao: 1 },
 ultimaAtt: "2h"
 },
 {
 id: 6, sigla: "XP", nome: "XP Investimentos", cor: "#FBBF24",
 processos: 9, urgentes: 0, prazoHoje: 0, prazoSemana: 1,
 valorRisco: 180000, taxaExito: 88,
 pipeline: { analise: 2, contestacao: 3, probatoria: 2, sentenca: 1, recurso: 1, execucao: 0 },
 ultimaAtt: "1d"
 },
];

const prazos = [
 { cliente: "LATAM Airlines", clienteCor: "#F0A500", processo: "0012345-67.2024.8.26.0100", tipo: "Contestação", prazo: "HOJE", dias: 0, urgencia: "critico" },
 { cliente: "Claro Brasil", clienteCor: "#34D399", processo: "0098765-43.2024.8.26.0050", tipo: "Recurso Ordinário", prazo: "HOJE", dias: 0, urgencia: "critico" },
 { cliente: "Vivo Telecom", clienteCor: "#F87171", processo: "0011111-22.2024.8.26.0200", tipo: "Impugnação", prazo: "Amanhã", dias: 1, urgencia: "alto" },
 { cliente: "LATAM Airlines", clienteCor: "#F0A500", processo: "0033333-44.2024.8.26.0100", tipo: "Memorial", prazo: "Amanhã", dias: 1, urgencia: "alto" },
 { cliente: "Banco Safra", clienteCor: "#60A5FA", processo: "0055555-88.2024.8.26.0400", tipo: "Contestação", prazo: "06 mar", dias: 2, urgencia: "alto" },
 { cliente: "Claro Brasil", clienteCor: "#34D399", processo: "0077777-11.2024.8.26.0300", tipo: "Réplica", prazo: "07 mar", dias: 3, urgencia: "medio" },
 { cliente: "LATAM Airlines", clienteCor: "#F0A500", processo: "0099999-55.2024.8.26.0100", tipo: "Agravo Interno", prazo: "10 mar", dias: 6, urgencia: "medio" },
 { cliente: "Magazine Luiza", clienteCor: "#A78BFA", processo: "0044444-66.2024.8.26.0500", tipo: "Recurso", prazo: "14 mar", dias: 9, urgencia: "baixo" },
];

const atividade = [
 { tipo: "decisao", cliente: "LATAM Airlines", cor: "#F0A500", msg: "Nova sentença desfavorável — Proc. 0033333", sub: "Vara Cível de Campinas • Dano Moral R$ 52.000", tempo: "8 min" },
 { tipo: "ai", cliente: "Claro Brasil", cor: "#34D399", msg: "AI gerou contestação completa — Proc. 0077777", sub: "12 páginas • Jurisprudência: 4 precedentes citados", tempo: "41 min" },
 { tipo: "prazo", cliente: "Vivo Telecom", cor: "#F87171", msg: "Prazo crítico amanhã — 2 processos", sub: "Impugnação + Agravo — ação imediata necessária", tempo: "1h" },
 { tipo: "upload", cliente: "Banco Safra", cor: "#60A5FA", msg: "Petição inicial recebida — Proc. 0055555", sub: "AI extraindo dados • Análise em 2 min", tempo: "2h" },
 { tipo: "ai", cliente: "Magazine Luiza", cor: "#A78BFA", msg: "Ficha de risco atualizada — 3 processos", sub: "Risco médio → baixo após documentos do cliente", tempo: "3h" },
 { tipo: "exito", cliente: "XP Investimentos", cor: "#10B981", msg: "Processo encerrado com êxito — Proc. 0066666", sub: "Improcedente total • R$ 38.000 de risco eliminado", tempo: "5h" },
];

const stageLabels = {
 analise: "Análise", contestacao: "Contestação", probatoria: "Probatória",
 sentenca: "Sentença", recurso: "Recurso", execucao: "Execução"
};

const urgCfg = {
 critico: { cor: C.red, bg: C.redBg, border: C.redBorder },
 alto: { cor: C.yellow, bg: C.yellowBg, border: C.yellowBorder },
 medio: { cor: C.blue, bg: C.blueBg, border: C.blueBorder },
 baixo: { cor: C.text3, bg: C.bg3 + "80", border: C.border1 },
};

const tipoIcon = { decisao: "⚖", ai: "◆", prazo: "◌", upload: "↑", exito: "✓" };

function SLabel({ children }) {
 return <div style={{ fontSize: 9, color: C.text3, letterSpacing: "0.1em", fontFamily: "IBM Plex Mono,monospace", textTransform: "uppercase", marginBottom: 14 }}>{children}</div>;
}

function Divider() {
 return <div style={{ width: 1, height: 16, background: C.border1 }} />;
}

export default function GlobalDashboard() {
 const [clienteHover, setClienteHover] = useState(null);
 const [navAtivo, setNavAtivo] = useState("dashboard");
 const [briefingAberto, setBriefingAberto] = useState(true);

 const totalProcessos = clientes.reduce((s, c) => s + c.processos, 0);
 const totalUrgentes = clientes.reduce((s, c) => s + c.urgentes, 0);
 const totalHoje = clientes.reduce((s, c) => s + c.prazoHoje, 0);
 const totalSemana = clientes.reduce((s, c) => s + c.prazoSemana, 0);
 const totalRisco = clientes.reduce((s, c) => s + c.valorRisco, 0);

 const globalPipeline = Object.keys(C.stages).filter(k => k !== "encerrado").map(key => ({
 key, label: stageLabels[key], cor: C.stages[key],
 total: clientes.reduce((s, c) => s + (c.pipeline[key] || 0), 0)
 }));
 const pipelineTotal = globalPipeline.reduce((s, p) => s + p.total, 0);

 const navItems = [
 { id: "dashboard", icon: "▣", label: "Dashboard" },
 { id: "clientes", icon: "◈", label: "Clientes" },
 { id: "processos", icon: "◫", label: "Processos" },
 { id: "prazos", icon: "◷", label: "Prazos" },
 { id: "pecas", icon: "◧", label: "Peças" },
 { id: "relatorios", icon: "◩", label: "Relatórios" },
 ];

 return (
 <div style={{ background: C.bg0, minHeight: "100vh", display: "flex", fontFamily: "Geist,'Segoe UI',sans-serif", color: C.text1 }}>
 {/* ... full component JSX ... */}
 </div>
 );
}
